### ISSUE TITLE
Mojibake problem: €“

### ISSUE THREAD

**Issue by MicroJackson** [rspeer/python-ftfy#146]
Hi,
```
U+20AC  €       [Sc] EURO SIGN
U+201C  “       [Pi] LEFT DOUBLE QUOTATION MARK
SHOULD BE:
U+002D  -       [Pd] HYPHEN-MINUS
```

Example:
> €“Echinacea en Salvia€“

Is it possible to fix this?

**Comment by rspeer** [comment]
For some reason, the initial â is missing from the mojibake sequence `â€“` here.

I'm unlikely to try to fix this because it would involve restoring information that is not there, and I can't come up with what sequence of operations would be likely to delete the character `â`.
