### ISSUE TITLE
Problem fixing "é›…é›…" (Chinese)

### ISSUE THREAD

**Issue by SuperIRabbit** [rspeer/python-ftfy#166]
To reproduce:
```
from ftfy import fix_encoding
word = "é›…é›…"
print("Method 1:" + fix_encoding(word))
print("Method 2:" + word.encode("cp1252").decode("utf8"))
```

Output (the output of method 2 is expected in this case):
> Method 1:é›…é›…
> Method 2:雅雅

**Comment by rspeer** [comment]
This case probably won't be fixed without more surrounding context, because "é›…" is text that's actually somewhat likely in French.
