### ISSUE TITLE
example that could work: "CU╔NTENOS EN ESPA╤OL"

### ISSUE THREAD

**Issue by bostick** [rspeer/python-ftfy#180]
Hello,

I ran into this on a printed Target receipt

It is supposed to be "CUÉNTENOS EN ESPAÑOL"

And the Python to fix the problem would be:

'CU╔NTENOS EN ESPA╤OL'
>>> _.encode("cp437").decode("latin-1")
'CUÉNTENOS EN ESPAÑOL'

But the problem is that fix_text does not handle this:

>>> print(ftfy.fix_text("CU╔NTENOS EN ESPA╤OL"))
CU╔NTENOS EN ESPA╤OL

![165063848_10100726625444050_6546539598514257078_n](https://user-images.githubusercontent.com/183619/124140218-4aafa600-da56-11eb-88b6-23d68f33355f.jpg)

**Comment by rspeer** [comment]
ha, great example of mojibake. This is a particular case of #18.
