### ISSUE TITLE
example that could work: RosÅ½

### ISSUE THREAD

**Issue by bostick** [rspeer/python-ftfy#181]
Hello,

I ran into this in a printed label in a supermarket for some wine.

This is an example of double encoding

Here is the Python that shows how the bad text was created:

>>> "Rosé"
'Rosé'
>>> _.encode("mac_roman").decode("cp1252")
'RosŽ'
>>> _.encode("utf_8").decode("cp1252")
'RosÅ½'
>>> 

The problem is that fix_encoding only fixes 1 level:

>>> print(ftfy.fix_encoding("RosÅ½"))
RosŽ

and then it gets stuck:

>>> print(ftfy.fix_encoding("RosŽ"))
RosŽ

![179060476_10100737413225250_4705143928367452_n](https://user-images.githubusercontent.com/183619/124140961-f658f600-da56-11eb-8b82-325d653bdb16.jpg)

**Comment by Perdjesk** [comment]
This looks like a duplicate of https://github.com/rspeer/python-ftfy/issues/18

**Comment by rspeer** [comment]
That's right -- without a much fancier heuristic, we can't tell that "RosŽ" isn't the correct string.
