### ISSUE TITLE
Incorrect link in README.md

### ISSUE THREAD

**Issue by Kristine1975** [rspeer/python-ftfy#182]
The link "Heuristics for detecting mojibake" at
https://github.com/rspeer/python-ftfy/blob/4e87b8cfde3a28e837a418544f7b840d0fa3adb7/README.md?plain=1#L19 leads to a 404 page: https://ftfy.readthedocs.io/en/v6.0/heuristics.html

The correct link is ("heuristic" singular instead of plural): https://ftfy.readthedocs.io/en/v6.0/heuristic.html

**Comment by rspeer** [comment]
Fixed, thanks!
