### ISSUE TITLE
Indicate existence of type annotations with py.typed file

### ISSUE THREAD

**Issue by bnewbold** [rspeer/python-ftfy#183]
As always, thank you for maintaining a library that fixes so much for so many!

It looks like `ftfy` has some partial type annotation coverage in the library itself, in particular on the `fix_text()` function: https://github.com/rspeer/python-ftfy/blob/master/ftfy/__init__.py#L244

However, when I run `mypy` on a downstream project (`fatcat-scholar`), which uses `ftfy 6.0.3`, I get:

    error: Skipping analyzing "ftfy": found module but no type hints or library stubs

Usually mypy's `--ignore-missing-imports` flag skips these errors, but in this case it seems like the annotations do already exist.

I think this is because `ftfy` does not include a PEP-561 `py.typed` stub file. This short blog post describes one way to add this file: https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/

Is this something you would be willing to include? I can contribute a patch if that is helpful.

**Comment by rspeer** [comment]
Fixed in version 6.1. Thanks!
