### ISSUE TITLE
6.0.3 appears broken with unicode fixes

### ISSUE THREAD

**Issue by rpasta42** [rspeer/python-ftfy#186]
Hello,
Please consider the following scenario:

```
import ftfy; ftfy.fix_encoding('wei√ü"')
```

The expected result is 'weiß"'.

This works correctly in 5.6 but breaks with 6.0.3.

<img width="616" alt="Screen Shot 2022-02-04 at 11 30 36 AM" src="https://user-images.githubusercontent.com/3255136/152566640-d21805b0-1f15-4bf8-af39-d800b5bb1864.png">

On an unrelated note, thank you for this amazing package, ftfy is awesome!

**Comment by rspeer** [comment]
Fixed in 6.1.1. Thanks!
