### ISSUE TITLE
On the wish list: "Pyreneeu00ebn" being explained as "Pyreneeën 71"

### ISSUE THREAD

**Issue by jpluimers** [rspeer/python-ftfy#191]
A while ago [I blogged](https://wiert.wordpress.com/?p=13500) about "Pyreneeën 71" on a web-site being incorrectly represented as "Pyreneeu00ebn".

Basically the Unicode code point `U+00EB : LATIN SMALL LETTER E WITH DIAERESIS` is being represented as `u00eb`.

Is this something that `ftfy` could potentially recognise?

Right now It does not:

``` text
>>> ftfy.fix_and_explain("Pyreneeu00ebn")
ExplainedText(text='Pyreneeu00ebn', explanation=[])
```

**Comment by kcarnold** [comment]
Presumably something is escaping the string and then stripping `\`s from it. You could try undoing this with some code that searched for all possible Unicode escapes (here, `u([0-9a-f]{4})`), tried putting a backslash in front (or just replacing it with the corresponding unicode codepoint), and seeing if the result "makes sense" by some logic that you determine (e.g., it's a character in a language you'd expect).
