### ISSUE TITLE
Add `source-code` and `issue-tracker` linkes to PyPI metadata of `ftfy`

### ISSUE THREAD

**Issue by sugatoray** [rspeer/python-ftfy#198]
The PyPI page does not share any details on where the repository is (source-code or issue-tracker). This makes it harder for people to find the GitHub repository from PyPI.

Add metadata for `source-code` and `issue-tracker` in the setup.py file so that PyPI automatically shows them on the page.

**Comment by rspeer** [comment]
I added [the appropriate fields to pyproject.toml](https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-pyproject-toml) per the docs. Do you know why this wouldn't have worked?

**Comment by rspeer** [comment]
okay, I figured it out. Python's documentation is insufficient because they delegate important details to third-party build systems, which all have their own approaches but you really can't get by without one.
