### ISSUE TITLE
windows-1257 not fix

### ISSUE THREAD

**Issue by JonhSilver** [rspeer/python-ftfy#210]
import ftfy
print(ftfy.fix_text('SÄ…raÅai'))

**Comment by rspeer** [comment]
This is true -- windows-1257 isn't currently on the list of encodings that gets fixed.

Would you be able to point me to somewhere that I'd find text files that were really encoded in windows-1257, or more examples of windows-1257 mojibake in the wild, so I could make heuristics and test cases out of it?

**Comment by NilsEnevoldsen** [comment]
TXT files here (i.e. files prior to 2004) are windows-1257 encoded.

http://zagarins.net/kjl/arhivs.html

**Comment by rspeer** [comment]
Wonderful, this looks like something I can make a heuristic out of for the next version.

**Comment by rspeer** [comment]
I've got a version that can fix text like `"Å veices baÅ†Ä·ieri gaida konkrÄ“tus investÄ«ciju projektus"`, but what was the example you originally gave supposed to become? It's got a Unicode private use character in it.

**Comment by rspeer** [comment]
Released in 6.3.
