### ISSUE TITLE
Build fail on manjaro

### ISSUE THREAD

**Issue by dynamodan** [rspeer/python-ftfy#215]
Building python-ftfy...
==> Making package: python-ftfy 6.2.3-1 (Fri 09 Aug 2024 06:21:26 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found python-ftfy-6.2.3.tar.gz
==> Validating source files with sha512sums...
    python-ftfy-6.2.3.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting python-ftfy-6.2.3.tar.gz with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
ERROR Failed to parse /var/tmp/pamac-build-dynamo/python-ftfy/src/ftfy-6.2.3/pyproject.toml: Invalid statement (at line 10, column 5) 
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by rspeer** [comment]
Thanks for letting me know - I'll take a look.

**Comment by rspeer** [comment]
Line 10, column 5 is the "u" in the word "include", so I'm very confused.

Can you give me the broader context? I don't know what Manjaro is or what it's trying to do. Is it trying to run a Poetry build, or parse the TOML in pyproject.toml with its own parser, or something else?

**Comment by rspeer** [comment]
I have double-checked that pyproject.toml is syntactically correct. The bug you're reporting is not in the ftfy codebase. It might be in some external script someone has written for Manjaro.

Whatever they're doing, it appears they're not parsing TOML correctly, but I don't understand why they'd need to bring their own TOML parser.

I recommend installing ftfy from the wheel, or using poetry if you want to install it from source yourself.

**Comment by eitan-j** [comment]
The issue is with the [line 20](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-ftfy#n20) in the AUR PKGBUILD. It messes up the pyproject.toml. You can fix it by removing the `prepare()` section from line 17-21 before building.
