### ISSUE TITLE
Unable to correctly handle the last character when fixing Chinese mojibake

### ISSUE THREAD

**Issue by laiyonghao** [rspeer/python-ftfy#217]
Hello,

When I tried to fix mojibake using ftfy version 6.2.3, the last character was always incorrect.

Please help me.

I have tried versions 6.2.0 and 6.1.3 and have encountered the same error.

Here are a few examples:

```
mojibake: 'Python åˆ\xa0é™¤åˆ—è¡¨ä¸\xadçš„å…ƒç´'
output: 'Python 删除列表中的元ç´'

mojibake: 'Puppeteer å¤„ç\x90†æ–‡ä»¶ä¸Šä¼'
output: 'Puppeteer 处理文件上ä¼'

mojibake: 'Diablo ç¬¬äºŒå¹• é²\x81 Â· é«˜å›'
output: 'Diablo 第二幕 鲁 · 高å›'
```

**Comment by laiyonghao** [comment]
I have found the reason, the original data is missing a byte, and it is not an issue with `ftfy`.

**Comment by rspeer** [comment]
Thanks for the followup!
